In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os, glob
import smartbee as sb

In [2]:
# Importing the dataset

'''O link em url possui os datasets do projeto, verificar qual se quer usar para passar como índice do datasets no read_csv
e qual pasta se colocará junto da url no get_files_paths!'''

base='https://raw.githubusercontent.com/rhanielmx/smartbee-files/master/Datasets/Bayer/'
url='https://github.com/rhanielmx/smartbee-files/tree/master/Datasets/'
ext=['csv']
datasets=sb.get_files_paths(url+'Bayer', ext)

#Colunas que vamos importar do dataset
#weight_col='hive_weight';temp_col='hive_temperature';humidity_col='hive_humidity';labels_col='KMeansLabel'
weight_col='Weight(lbs)';temp_hive_col='Temp-Hive(F)';temp_brood_col='Temp-Brood(F)';humidity_hive_col='HRH(%)';humidity_brood_col='BRH(%)';labels_col='Code_Label'

In [3]:
# Importing the dataset
data = pd.read_csv(base+datasets[0][0],usecols=(weight_col, temp_hive_col, temp_brood_col, humidity_hive_col, humidity_brood_col, labels_col))
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [4]:
#Splitting dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [5]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [6]:
# Fitting classifier to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [7]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [8]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
sr = 100*(cm.diagonal().sum()/cm.sum())

In [9]:
print(f'Taxa de Acerto: {sr:0.2f}%')
print(f'Matriz de Confusão: \n {cm}')

Taxa de Acerto: 61.11%
Matriz de Confusão: 
 [[ 0  0  1]
 [ 0 15  3]
 [ 0 10  7]]


In [10]:
for i in range(X_train.shape[1]):
    for j in range(len(np.unique(y_train))):
        mean=np.mean([X_train[ind][i] for ind in range(len(X_train)) if y_train[ind]==j])
        print(f'Mean of {data.columns[j]} in class {i}:{mean:.4f}')
    print('')

Mean of Temp-Brood(F) in class 0:-0.0581
Mean of Temp-Hive(F) in class 0:-0.5705
Mean of BRH(%) in class 0:-0.1747
Mean of HRH(%) in class 0:0.2892

Mean of Temp-Brood(F) in class 1:-0.7848
Mean of Temp-Hive(F) in class 1:-0.6154
Mean of BRH(%) in class 1:0.0847
Mean of HRH(%) in class 1:-0.0352

Mean of Temp-Brood(F) in class 2:-1.7613
Mean of Temp-Hive(F) in class 2:-0.4956
Mean of BRH(%) in class 2:0.0918
Mean of HRH(%) in class 2:-0.0215

Mean of Temp-Brood(F) in class 3:-2.5208
Mean of Temp-Hive(F) in class 3:-0.0785
Mean of BRH(%) in class 3:0.1119
Mean of HRH(%) in class 3:-0.0587

Mean of Temp-Brood(F) in class 4:0.4116
Mean of Temp-Hive(F) in class 4:0.4384
Mean of BRH(%) in class 4:-0.3730
Mean of HRH(%) in class 4:0.4560



In [11]:
for i in range(X_train.shape[1]):
    for j in range(len(np.unique(y_train))):
        std=np.std([X_train[ind][i] for ind in range(len(X_train)) if y_train[ind]==j])
        print(f'Standard Deviation of {data.columns[j]} in class {i}:\t{std:.4f}')
    print('')

Standard Deviation of Temp-Brood(F) in class 0:	0.1137
Standard Deviation of Temp-Hive(F) in class 0:	0.4601
Standard Deviation of BRH(%) in class 0:	0.9978
Standard Deviation of HRH(%) in class 0:	0.9770

Standard Deviation of Temp-Brood(F) in class 1:	0.0000
Standard Deviation of Temp-Hive(F) in class 1:	0.3600
Standard Deviation of BRH(%) in class 1:	0.9708
Standard Deviation of HRH(%) in class 1:	1.0598

Standard Deviation of Temp-Brood(F) in class 2:	0.1652
Standard Deviation of Temp-Hive(F) in class 2:	0.2452
Standard Deviation of BRH(%) in class 2:	0.9999
Standard Deviation of HRH(%) in class 2:	0.9872

Standard Deviation of Temp-Brood(F) in class 3:	0.6134
Standard Deviation of Temp-Hive(F) in class 3:	0.2378
Standard Deviation of BRH(%) in class 3:	0.9683
Standard Deviation of HRH(%) in class 3:	0.9734

Standard Deviation of Temp-Brood(F) in class 4:	0.1074
Standard Deviation of Temp-Hive(F) in class 4:	0.1719
Standard Deviation of BRH(%) in class 4:	0.9966
Standard Deviation 

In [18]:
def main():    
    for _ in range(n_rounds):
        # Importing the dataset
        data = pd.read_csv(path,usecols=(weight_col, temp_hive_col, temp_brood_col, humidity_hive_col, humidity_brood_col, labels_col))
        X = data.iloc[:, :-1].values
        y = data.iloc[:, -1].values
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

        clf = GaussianNB()
        clf.fit(X_train,y_train)
        preds=clf.predict(X_test)    
        
        cm = confusion_matrix(y_test, preds)
        sr = 100*(cm.diagonal().sum()/cm.sum())
        confusion_matrixes.append(cm)
        accuracys.append(sr)
        
        '''class0_success=100*cm[0][0]/(cm[0][0]+cm[0][1])
        class1_success=100*cm[1][1]/(cm[1][0]+cm[1][1])
         
        class0_successes.append(class0_success)
        class1_successes.append(class1_success)'''

        if ((_+1)%(int(n_rounds/10))==0):
            print(f'{(_+1)*(100/n_rounds):05.2f}% concluído!')

In [19]:
path=base+datasets[0][0]
accuracys = []
confusion_matrixes = []
n_rounds=50

%time main()

10.00% concluído!
20.00% concluído!
30.00% concluído!
40.00% concluído!
50.00% concluído!
60.00% concluído!
70.00% concluído!
80.00% concluído!
90.00% concluído!
100.00% concluído!
Wall time: 11.9 s


In [20]:
Accuracys=pd.DataFrame(data={'Accuracys':accuracys})
Accuracys.describe()

Accuracys
count  50.000000
mean   63.055556
std     7.638245
min    44.444444
25%    58.333333
50%    63.888889
75%    69.444444
max    80.555556

In [21]:
path=base+datasets[0][1]
accuracys = []
confusion_matrixes = []
n_rounds=50

%time main()

ValueError: Usecols do not match names.

In [16]:
Accuracys1=pd.DataFrame(data={'Accuracys':accuracys})
Accuracys1.describe()

Accuracys
count        0.0
mean         NaN
std          NaN
min          NaN
25%          NaN
50%          NaN
75%          NaN
max          NaN

In [17]:
confusion_matrixes

[]